apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: mlflow-infisical-sync
  namespace: mlflow
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical-operator
  syncOptions:
    refreshInterval: 1m
    instantUpdates: false
  sources:
    - projectSlug: "mlops-kzbk"
      environmentSlug: "dev"
      secretPath: "/"
  targets:
    - name: mlflow-managed-secret
      namespace: mlflow
      kind: Secret
      creationPolicy: Owner