apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow
spec:
  ingressClassName: nginx
  rules:
  - host: mlflow.local.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mlflow-service
            port:
              number: 80
