apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencloud-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: "https://github.com/redhox/k8s.git"
    targetRevision: main
    path: opencloud/dev

  destination:
    server: "https://kubernetes.default.svc"
    namespace: opencloud

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
