apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-navidrome-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-navidrome-music
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /storage_nfs/musique
    server: 192.168.1.186
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-navidrome-music
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: pv-navidrome-music
  storageClassName: "" 
  resources:
    requests:
      storage: 20Gi
