apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  custom.config.php: |
    <?php
    $CONFIG = array (
      'trusted_domains' =>
      array (
        0 => 'cloud.local.co',
      ),
        
    );



