apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  config.php: |
    <?php
    $CONFIG = array (
      'overwrite.cli.url' => 'http://cloud.local.co',
      'trusted_domains' =>
      array (
        0 => 'cloud.local.co',
      ),
      'dbtype' => 'pgsql',
      'dbname' => 'nextcloud',
      'dbhost' => '10.0.2.40:5432',
      'dbuser' => 'myuser',
      'dbpassword' => getenv('POSTGRES_PASSWORD'),
      'installed' => true,
      'objectstore' => array(
        'class' => '\\OC\\Files\\ObjectStore\\S3',
        'arguments' => array(
          'bucket' => 'api-label',
          'autocreate' => true,
          'key'    => getenv('OBJECTSTORE_S3_KEY'),
          'secret' => getenv('OBJECTSTORE_S3_SECRET'),
          'region' => 'us-east-1',
          'hostname' => 'bucket.morgan-coulm.fr',
          'port' => 9000,
          'use_ssl' => true,
          'use_path_style' => true,
        ),
      ),
    );

