apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  custom.config.php: |
    <?php
    $CONFIG = array (
      'trusted_domains' =>
      array (
        0 => 'cloud.local.co',
      ),
      'datadirectory' => '/var/www/html/data',
      'dbtype' => 'pgsql',
      'dbname' => 'nextcloud',
      'dbhost' => '10.0.2.40',
      'dbport' => '5432',
      'dbuser' => 'myuser',
      'dbpassword' => 'mypassword',
      'installed' => true,
    );



