apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:latest
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: "http://10.0.2.40"
            - name: POSTGRES_DB
              value: "nextcloud"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: NEXTCLOUD_ADMIN_USER
              value: "admin"
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "adminpassword"

            - name: OBJECTSTORE_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: bucket-secret
                  key: BUCKET_NAME
            - name: OBJECTSTORE_S3_KEY
              valueFrom:
                secretKeyRef:
                  name: bucket-secret
                  key: AWS_ACCESS_KEY_ID
            - name: OBJECTSTORE_S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: bucket-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: OBJECTSTORE_S3_REGION
              value: "us-east-1"
            - name: OBJECTSTORE_S3_HOST
              value: "s3.amazonaws.com"
            - name: OBJECTSTORE_S3_PORT
              value: "443"
            - name: OBJECTSTORE_S3_SSL
              value: "true"

          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html
            - name: nextcloud-config
              mountPath: /var/www/html/config/config.php
              subPath: config.php
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc
        - name: nextcloud-config
          configMap:
            name: nextcloud-config
