resources:
  - namespace.yaml
  - secrete.yaml
  - ingress.yaml

helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    releaseName: nextcloud
    namespace: postgresql
    valuesFile: nextcloud/dev/values.yaml
    version: 4.5.0  # à adapter selon la dernière version stable
