livenessProbe:
  enabled: false

readinessProbe:
  enabled: false


persistence:
  enabled: true
  storageClass: longhorn
  size: 5Gi
  accessMode: ReadWriteOnce

nextcloud:
  host: cloud.local.co
  username: admin
  password: admin
  datadir: /var/www/html/data

  extraEnv:
    - name: "NC_primary_storage"
      value: "s3"
    - name: "S3_BUCKET"
      value: "api-label"
    - name: "S3_KEY"
      valueFrom:
        secretKeyRef:
          name: bucket-secret
          key: AWS_ACCESS_KEY_ID
    - name: "S3_SECRET"
      valueFrom:
        secretKeyRef:
          name: bucket-secret
          key: AWS_SECRET_ACCESS_KEY
    - name: "S3_HOST"
      value: "bucket.morgan-coulm.fr"
    - name: "S3_PORT"
      value: "9000"
    - name: "S3_SSL"
      value: "true"
    - name: "S3_USEPATH_STYLE"
      value: "true"


