apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: opencloud-infisical-sync
  namespace: opencloud
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical-operator
  syncOptions:
    refreshInterval: 1m
    instantUpdates: false
  sources:
    - projectSlug: "opencloud-dul-d"
      environmentSlug: "dev"
      secretPath: "/"
  targets:
    - name: opencloud-managed-secret
      namespace: opencloud
      kind: Secret
      creationPolicy: Owner