global:
  domain:
    opencloud: cloud.morgan-coulm.fr

  tls:
    enabled: false

opencloud:
  enabled: true
  replicas: 1

  existingSecret: opencloud-admin

  createDemoUsers: false

  persistence:
    config:
      enabled: true
      size: 5Gi

    data:
      enabled: true
      size: 30Gi

  storage:
    mode: s3

    s3:
      internal:
        enabled: false

      external:
        enabled: true
        endpoint: "https://bucket.morgan-coulm.fr"
        region: "us-east-1"

        existingSecret: opencloud-s3

        bucket: "opencloud"
        createBucket: false

keycloak:
  internal:
    enabled: true
    existingSecret: opencloud-keycloak

postgres:
  enabled: true
  existingSecret: opencloud-postgres

ingress:
  enabled: true
  ingressClassName: nginx
