apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: dijigue 
    fsType: ext4
