apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: postgresql
  name: jupyterhub-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete"]
