apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/redhox/k8s.git
    targetRevision: HEAD
    path: mlflow/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: postgresql

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
